export const defaultEnGherkin = [
	"Feature: Calculator",
	"",
	"Simple calculator for adding two numbers",
	"",
	"@mytag",
	"Background:",
	'Given a global administrator named "Greg"',
	"",
	"# The first example has two steps",
	"@mytag",
	"Scenario: Add two numbers",
	"Given I have entered 50 into the calculator",
	"# My comment",
	"And I have entered 70 into the calculator",
	"When I press add",
	"Then the result should be 120 on the screen",
	"",
	"@mytag",
	"Scenario Outline: Add two numbers",
	"Given I have entered <First> in the calculator",
	"And I have entered <Second> into the calculator",
	"When I press add",
	"Then the result should be <Result> on the screen <Result>",
	"",
	"Examples:",
	"  |   First    |  Second |   Result |",
	"  | 50    | 70     | 120    |",
	"  | 30    | 40     | 70     |",
	"  | 60    | 30     | 90     |",
].join("\n");

export const defaultFrGherkin = [
	"Fonctionnalité: Calculatrice",
	"",
	"Calculatrice simple pour additionner deux nombres",
	"",
	"@mytag",
	"Contexte:",
	"Soit un administrateur global nommé «Greg»",
	"",
	"# Le premier exemple comporte deux étapes",
	"@mytag",
	"Scénario: Additionner deux nombres",
	"Soit j'ai saisi 50 dans la calculatrice",
	"# Mon commentaire",
	"Et j'ai saisi 70 dans la calculatrice",
	"Lorsque j'appuie sur «Addition», le résultat devrait être 120 à l'écran",
	"",
	"@mytag",
	"Scénario: Additionner deux nombres",
	"Soit j'ai saisi <Premier> dans la calculatrice",
	"Et j'ai saisi <Second> dans la calculatrice",
	"Lorsque j'appuie sur «Addition», le résultat devrait être <Résultat> à l'écran <Résultat>",
	"",
	"Exemples:",
	"| Premier | Second | Résultat |",
	"| 50 | 70 | 120 |",
	"| 30 | 40 | 70 |",
	"| 60 | 30 | 90 |",
].join("\n");
